export const currentUser = {
    image: "./images/userImage.png",
    name: "Mark Carson",
    email: "abc@xyz.com"
}

export const stats = [
    {
        id: 1,
        image: "./images/stats1.png",
        number: "100",
        text: "Male",
        change: "100",
        increase: true,
    },
    {
        id: 2,
        image: "./images/stats2.png",
        number: "80",
        text: "Female",
        change: "75",
        increase: true,
    },
    {
        id: 3,
        image: "./images/stats3.png",
        number: "180",
        text: "Total Users",
        change: "22",
        increase: false,
    },
]

export const maleData = [
    {
        id: 1,
        status: true,
        image: "./images/male1.jpg",
        gender: "Male",
        name: "John Doe",
        username: "john.doe",
        email: "john@email.com",
        phone: "+1-123-456-789",
        registered: "08/10/2022",
        age: "25",
        location: "Abc address",
        about:
            "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Swimming", "Movies", "Nightout"],
    },
    {
        id: 2,
        status: true,
        image: "./images/male2.jpg",
        gender: "Male",
        name: "Mark Jason",
        username: "mark.jason",
        email: "mark@email.com",
        phone: "+1-321-666-789",
        registered: "02/10/2022",
        age: "24",
        location: "Xyz address",
        about:
            "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing.",
        interest: ["Reading", "Movies", "Painting"],
    },
    {
        id: 3,
        status: false,
        image: "./images/male3.jpg",
        gender: "Male",
        name: "Mike Roy",
        username: "mike.roy",
        email: "mikeroy@email.com",
        phone: "+1-525-864-125",
        registered: "26/09/2022",
        age: "27",
        location: "Abc street address",
        about:
            "simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Football", "Rafting", "Nightout"],
    },
    {
        id: 4,
        status: true,
        image: "./images/male4.jpg",
        gender: "Male",
        name: "Will Byers",
        username: "byers.will",
        email: "will@email.com",
        phone: "+1-985-999-625",
        registered: "22/09/2022",
        age: "19",
        location: "Xyz address",
        about:
            "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Painting", "Writing", "Gaming"],
    },
    {
        id: 5,
        status: false,
        image: "./images/male2.jpg",
        gender: "Male",
        name: "Isidro Haris",
        username: "isidro",
        email: "isidro@email.com",
        phone: "+1-206-396-1973",
        registered: "22/09/2022",
        age: "31",
        location: "Abc address",
        about:
            "Lorem Ipsum is text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Shooting", "Baseball", "Boxing"],
    },
    {
        id: 6,
        status: true,
        image: "./images/male3.jpg",
        gender: "Male",
        name: "James Doe",
        username: "james.doe",
        email: "james.doe@email.com",
        phone: "+1-984-456-987",
        registered: "18/09/2022",
        age: "20",
        location: "Abc address",
        about:
            "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Swimming", "Gaming", "Movies", "Surfing"],
    },
];

export const femaleData = [
    {
        id: 1,
        status: true,
        image: "./images/female1.jpg",
        gender: "Female",
        name: "Ogasawara Katsumi",
        username: "ogasawara.katsumi",
        email: "ogasawara@email.com",
        phone: "+1-123-456-789",
        registered: "08/10/2022",
        age: "25",
        location: "Abc address",
        about:
            "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Swimming", "Movies", "Nightout"],
        price: "20",
        commission: "10",
    },
    {
        id: 2,
        status: true,
        image: "./images/female2.jpg",
        gender: "Female",
        name: "Stepan Assonov",
        username: "stepan.assonov",
        email: "stepan@email.com",
        phone: "+1-321-666-789",
        registered: "02/10/2022",
        age: "24",
        location: "Xyz address",
        about:
            "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing.",
        interest: ["Reading", "Movies", "Painting"],
        price: "30",
        commission: "20",
    },
    {
        id: 3,
        status: false,
        image: "./images/female3.jpg",
        gender: "Female",
        name: "Lucas Pacheco",
        username: "lucas.pacheco",
        email: "Lucas@email.com",
        phone: "+1-525-864-125",
        registered: "26/09/2022",
        age: "27",
        location: "Abc street address",
        about:
            "simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Football", "Rafting", "Nightout"],
        price: "20",
        commission: "15",
    },
    {
        id: 4,
        status: true,
        image: "./images/female4.jpg",
        gender: "Female",
        name: " Marco Alves",
        username: "marco.alves",
        email: "marco.alves@email.com",
        phone: "+1-985-999-625",
        registered: "22/09/2022",
        age: "19",
        location: "Xyz address",
        about:
            "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Painting", "Writing", "Gaming"],
        price: "15",
        commission: "10",
    },
    {
        id: 5,
        status: false,
        image: "./images/female2.jpg",
        gender: "Female",
        name: "Mbe Tshinguta",
        username: "tshinguta",
        email: "mbe.tshinguta@email.com",
        phone: "+1-206-396-1973",
        registered: "22/09/2022",
        age: "31",
        location: "Abc address",
        about:
            "Lorem Ipsum is text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Shooting", "Baseball", "Boxing"],
        price: "10",
        commission: "15",
    },
    {
        id: 6,
        status: true,
        image: "./images/female3.jpg",
        gender: "Female",
        name: "Okasawara Karsumi",
        username: "okasawara.karsumi",
        email: "okasawara@email.com",
        phone: "+1-984-456-987",
        registered: "18/09/2022",
        age: "20",
        location: "Abc address",
        about:
            "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Swimming", "Gaming", "Movies", "Surfing"],
        price: "25",
        commission: "13",
    },
];

export const paymentLog = [
    {
        id: 1,
        male: {
            id: 1,
            status: true,
            image: "./images/male1.jpg",
            gender: "Male",
            name: "John Doe",
            username: "john.doe",
            email: "john@email.com",
            phone: "+1-123-456-789",
            registered: "08/10/2022",
            age: "25",
            location: "Abc address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Swimming", "Movies", "Nightout"],
        },
        female: {
            id: 1,
            status: true,
            image: "./images/female1.jpg",
            gender: "Female",
            name: "Ogasawara Katsumi",
            username: "ogasawara.katsumi",
            email: "ogasawara@email.com",
            phone: "+1-123-456-789",
            registered: "08/10/2022",
            age: "25",
            location: "Abc address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Swimming", "Movies", "Nightout"],
            price: "20",
            commission: "10",
        },
        price: 20,
        commission: 10,
        femaleRevenue: 10,
        dateScheduled: '20/02/2022',
        datePaid: '24/02/2022',
        status: true
    },
    {
        id: 2,
        male: {
            id: 1,
            status: true,
            image: "./images/male1.jpg",
            gender: "Male",
            name: "John Doe",
            username: "john.doe",
            email: "john@email.com",
            phone: "+1-123-456-789",
            registered: "08/10/2022",
            age: "25",
            location: "Abc address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Swimming", "Movies", "Nightout"],
        },
        female: {
            id: 2,
            status: true,
            image: "./images/female2.jpg",
            gender: "Female",
            name: "Stepan Assonov",
            username: "stepan.assonov",
            email: "stepan@email.com",
            phone: "+1-321-666-789",
            registered: "02/10/2022",
            age: "24",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing.",
            interest: ["Reading", "Movies", "Painting"],
            price: "30",
            commission: "20",
        },
        price: 40,
        commission: 15,
        femaleRevenue: 25,
        dateScheduled: '18/02/2022',
        datePaid: '19/02/2022',
        status: true
    },
    {
        id: 3,
        male: {
            id: 3,
            status: false,
            image: "./images/male3.jpg",
            gender: "Male",
            name: "Mike Roy",
            username: "mike.roy",
            email: "mikeroy@email.com",
            phone: "+1-525-864-125",
            registered: "26/09/2022",
            age: "27",
            location: "Abc street address",
            about:
                "simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Football", "Rafting", "Nightout"],
        },
        female: {
            id: 5,
            status: false,
            image: "./images/female2.jpg",
            gender: "Female",
            name: "Mbe Tshinguta",
            username: "tshinguta",
            email: "mbe.tshinguta@email.com",
            phone: "+1-206-396-1973",
            registered: "22/09/2022",
            age: "31",
            location: "Abc address",
            about:
                "Lorem Ipsum is text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Shooting", "Baseball", "Boxing"],
            price: "10",
            commission: "15",
        },
        price: 10,
        commission: 2,
        femaleRevenue: 8,
        dateScheduled: '18/02/2022',
        datePaid: '18/02/2022',
        status: false
    },
    {
        id: 4,
        male: {
            id: 6,
            status: true,
            image: "./images/male3.jpg",
            gender: "Male",
            name: "James Doe",
            username: "james.doe",
            email: "james.doe@email.com",
            phone: "+1-984-456-987",
            registered: "18/09/2022",
            age: "20",
            location: "Abc address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Swimming", "Gaming", "Movies", "Surfing"],
        },
        female: {
            id: 3,
            status: false,
            image: "./images/female3.jpg",
            gender: "Female",
            name: "Lucas Pacheco",
            username: "lucas.pacheco",
            email: "Lucas@email.com",
            phone: "+1-525-864-125",
            registered: "26/09/2022",
            age: "27",
            location: "Abc street address",
            about:
                "simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Football", "Rafting", "Nightout"],
            price: "20",
            commission: "15",
        },
        price: 40,
        commission: 10,
        femaleRevenue: 30,
        dateScheduled: '12/02/2022',
        datePaid: '16/02/2022',
        status: true
    },
    {
        id: 5,
        male: {
            id: 2,
            status: true,
            image: "./images/male2.jpg",
            gender: "Male",
            name: "Mark Jason",
            username: "mark.jason",
            email: "mark@email.com",
            phone: "+1-321-666-789",
            registered: "02/10/2022",
            age: "24",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing.",
            interest: ["Reading", "Movies", "Painting"],
        },
        female: {
            id: 4,
            status: true,
            image: "./images/female4.jpg",
            gender: "Female",
            name: " Marco Alves",
            username: "marco.alves",
            email: "marco.alves@email.com",
            phone: "+1-985-999-625",
            registered: "22/09/2022",
            age: "19",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Painting", "Writing", "Gaming"],
            price: "15",
            commission: "10",
        },
        price: 50,
        commission: 15,
        femaleRevenue: 35,
        dateScheduled: '11/02/2022',
        datePaid: '12/02/2022',
        status: true
    },
    {
        id: 6,
        male: {
            id: 5,
            status: false,
            image: "./images/male2.jpg",
            gender: "Male",
            name: "Isidro Haris",
            username: "isidro",
            email: "isidro@email.com",
            phone: "+1-206-396-1973",
            registered: "22/09/2022",
            age: "31",
            location: "Abc address",
            about:
                "Lorem Ipsum is text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Shooting", "Baseball", "Boxing"],
        },
        female: {
            id: 2,
            status: true,
            image: "./images/female2.jpg",
            gender: "Female",
            name: "Stepan Assonov",
            username: "stepan.assonov",
            email: "stepan@email.com",
            phone: "+1-321-666-789",
            registered: "02/10/2022",
            age: "24",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing.",
            interest: ["Reading", "Movies", "Painting"],
            price: "30",
            commission: "20",
        },
        price: 20,
        commission: 10,
        femaleRevenue: 10,
        dateScheduled: '06/02/2022',
        datePaid: '10/02/2022',
        status: false
    },
    {
        id: 7,
        male: {
            id: 4,
            status: true,
            image: "./images/male4.jpg",
            gender: "Male",
            name: "Will Byers",
            username: "byers.will",
            email: "will@email.com",
            phone: "+1-985-999-625",
            registered: "22/09/2022",
            age: "19",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Painting", "Writing", "Gaming"],
        },
        female: {
            id: 4,
            status: true,
            image: "./images/female4.jpg",
            gender: "Female",
            name: " Marco Alves",
            username: "marco.alves",
            email: "marco.alves@email.com",
            phone: "+1-985-999-625",
            registered: "22/09/2022",
            age: "19",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Painting", "Writing", "Gaming"],
            price: "15",
            commission: "10",
        },
        price: 25,
        commission: 5,
        femaleRevenue: 20,
        dateScheduled: '05/02/2022',
        datePaid: '06/02/2022',
        status: false
    },
    {
        id: 8,
        male: {
            id: 3,
            status: false,
            image: "./images/male3.jpg",
            gender: "Male",
            name: "Mike Roy",
            username: "mike.roy",
            email: "mikeroy@email.com",
            phone: "+1-525-864-125",
            registered: "26/09/2022",
            age: "27",
            location: "Abc street address",
            about:
                "simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Football", "Rafting", "Nightout"],
        },
        female: {
            id: 6,
            status: true,
            image: "./images/female3.jpg",
            gender: "Female",
            name: "Okasawara Karsumi",
            username: "okasawara.karsumi",
            email: "okasawara@email.com",
            phone: "+1-984-456-987",
            registered: "18/09/2022",
            age: "20",
            location: "Abc address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Swimming", "Gaming", "Movies", "Surfing"],
            price: "25",
            commission: "13",
        },
        price: 45,
        commission: 20,
        femaleRevenue: 25,
        dateScheduled: '20/02/2022',
        datePaid: '24/02/2022',
        status: true
    },
    {
        id: 9,
        male: {
            id: 3,
            status: false,
            image: "./images/male3.jpg",
            gender: "Male",
            name: "Mike Roy",
            username: "mike.roy",
            email: "mikeroy@email.com",
            phone: "+1-525-864-125",
            registered: "26/09/2022",
            age: "27",
            location: "Abc street address",
            about:
                "simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Football", "Rafting", "Nightout"],
        },
        female: {
            id: 4,
            status: true,
            image: "./images/female4.jpg",
            gender: "Female",
            name: " Marco Alves",
            username: "marco.alves",
            email: "marco.alves@email.com",
            phone: "+1-985-999-625",
            registered: "22/09/2022",
            age: "19",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Painting", "Writing", "Gaming"],
            price: "15",
            commission: "10",
        },
        price: 20,
        commission: 5,
        femaleRevenue: 15,
        dateScheduled: '20/02/2022',
        datePaid: '24/02/2022',
        status: false
    },
    {
        id: 10,
        male: {
            id: 5,
            status: false,
            image: "./images/male2.jpg",
            gender: "Male",
            name: "Isidro Haris",
            username: "isidro",
            email: "isidro@email.com",
            phone: "+1-206-396-1973",
            registered: "22/09/2022",
            age: "31",
            location: "Abc address",
            about:
                "Lorem Ipsum is text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Shooting", "Baseball", "Boxing"],
        },
        female: {
            id: 1,
            status: true,
            image: "./images/female1.jpg",
            gender: "Female",
            name: "Ogasawara Katsumi",
            username: "ogasawara.katsumi",
            email: "ogasawara@email.com",
            phone: "+1-123-456-789",
            registered: "08/10/2022",
            age: "25",
            location: "Abc address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Swimming", "Movies", "Nightout"],
            price: "20",
            commission: "10",
        },
        price: 15,
        commission: 5,
        femaleRevenue: 10,
        dateScheduled: '20/02/2022',
        datePaid: '24/02/2022',
        status: false
    },
];

export const femaleApplicants = [
    {
        id: 1,
        image: "./images/female1.jpg",
        name: "Ogasawara Katsumi",
        username: "ogasawara.katsumi",
        email: "ogasawara@email.com",
        phone: "+1-123-456-789",
        age: "25",
        location: "Abc address",
        about:
            "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Swimming", "Movies", "Nightout"],
        price: "20",
    },
    {
        id: 2,
        image: "./images/female2.jpg",
        name: "Stepan Assonov",
        username: "stepan.assonov",
        email: "stepan@email.com",
        phone: "+1-321-666-789",
        age: "24",
        location: "Xyz address",
        about:
            "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing.",
        interest: ["Reading", "Movies", "Painting"],
        price: "30",
    },
    {
        id: 3,
        image: "./images/female3.jpg",
        name: "Lucas Pacheco",
        username: "lucas.pacheco",
        email: "Lucas@email.com",
        phone: "+1-525-864-125",
        age: "27",
        location: "Abc street address",
        about:
            "simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Football", "Rafting", "Nightout"],
        price: "20",
    },
    {
        id: 4,
        image: "./images/female4.jpg",
        name: " Marco Alves",
        username: "marco.alves",
        email: "marco.alves@email.com",
        phone: "+1-985-999-625",
        age: "19",
        location: "Xyz address",
        about:
            "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Painting", "Writing", "Gaming"],
        price: "15",
    },
    {
        id: 5,
        image: "./images/female2.jpg",
        name: "Mbe Tshinguta",
        username: "tshinguta",
        email: "mbe.tshinguta@email.com",
        phone: "+1-206-396-1973",
        age: "31",
        location: "Abc address",
        about:
            "Lorem Ipsum is text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Shooting", "Baseball", "Boxing"],
        price: "10",
    },
    {
        id: 6,
        image: "./images/female3.jpg",
        name: "Okasawara Karsumi",
        username: "okasawara.karsumi",
        email: "okasawara@email.com",
        phone: "+1-984-456-987",
        registered: "18/09/2022",
        age: "20",
        location: "Abc address",
        about:
            "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        interest: ["Swimming", "Gaming", "Movies", "Surfing"],
        price: "25",
    },
];

export const commissionLogs = [
    {
        id: 1,
        oldCommission: 15,
        newCommission: 20,
        updatedDate: "10/05/2022",
        effectiveDate: "15/05/2022"
    },
    {
        id: 2,
        oldCommission: 20,
        newCommission: 12,
        updatedDate: "05/02/2022",
        effectiveDate: "22/02/2022"
    },
    {
        id: 3,
        oldCommission: 12,
        newCommission: 15,
        updatedDate: "10/01/2022",
        effectiveDate: "20/01/2022"
    },
    {
        id: 4,
        oldCommission: 15,
        newCommission: 18,
        updatedDate: "19/11/2021",
        effectiveDate: "30/11/2021"
    },
    {
        id: 5,
        oldCommission: 18,
        newCommission: 12,
        updatedDate: "10/10/2021",
        effectiveDate: "20/10/2021"
    },
    {
        id: 6,
        oldCommission: 12,
        newCommission: 15,
        updatedDate: "16/07/2021",
        effectiveDate: "02/08/2021"
    },
];

export const feedbacks = [
    {
        id: 1,
        user: {
            id: 1,
            status: true,
            gender: "Male",
            image: "./images/male1.jpg",
            name: "John Doe",
            username: "john.doe",
            email: "john@email.com",
            phone: "+1-123-456-789",
            registered: "08/10/2022",
            age: "25",
            location: "Abc address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Swimming", "Movies", "Nightout"],
        },
        subject: "Abc",
        message: "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        date: "19/12/2022"
    },
    {
        id: 2,
        user: {
            id: 3,
            status: false,
            image: "./images/male3.jpg",
            gender: "Male",
            name: "Mike Roy",
            username: "mike.roy",
            email: "mikeroy@email.com",
            phone: "+1-525-864-125",
            registered: "26/09/2022",
            age: "27",
            location: "Abc street address",
            about:
                "simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Football", "Rafting", "Nightout"],
        },
        subject: "Xyz",
        message: "Lorem Ipsum is text of printing & typesetting industry of printing & typesetting industry.",
        date: "01/12/2022"
    },
    {
        id: 3,
        user: {
            id: 4,
            status: true,
            image: "./images/female4.jpg",
            gender: "Female",
            name: " Marco Alves",
            username: "marco.alves",
            email: "marco.alves@email.com",
            phone: "+1-985-999-625",
            registered: "22/09/2022",
            age: "19",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Painting", "Writing", "Gaming"],
            price: "15",
            commission: "10",
        },
        subject: "Abc Subject",
        message: "Lorem text of printing & typesetting industry of printing & typesetting industry.",
        date: "22/11/2022"
    },
    {
        id: 4,
        user: {
            id: 1,
            status: true,
            image: "./images/male1.jpg",
            gender: "Male",
            name: "John Doe",
            username: "john.doe",
            email: "john@email.com",
            phone: "+1-123-456-789",
            registered: "08/10/2022",
            age: "25",
            location: "Abc address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Swimming", "Movies", "Nightout"],
        },
        subject: "Xyz Subject",
        message: "Lorem Ipsum is text of printing & typesetting industry of printing.",
        date: "11/11/2022"
    },
    {
        id: 5,
        user: {
            id: 2,
            status: true,
            image: "./images/female2.jpg",
            gender: "Female",
            name: "Stepan Assonov",
            username: "stepan.assonov",
            email: "stepan@email.com",
            phone: "+1-321-666-789",
            registered: "02/10/2022",
            age: "24",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing.",
            interest: ["Reading", "Movies", "Painting"],
            price: "30",
            commission: "20",
        },
        subject: "Abc 123 Subject",
        message: "Lorem Ipsum is text of printing & typesetting industry of printing & typesetting industry.",
        date: "29/09/2022"
    },
];

export const reports = [
    {
        id: 1,
        user: {
            id: 1,
            image: "./images/female1.jpg",
            name: "Ogasawara Katsumi",
            username: "ogasawara.katsumi",
            email: "ogasawara@email.com",
            phone: "+1-123-456-789",
            age: "25",
            location: "Abc address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Swimming", "Movies", "Nightout"],
            price: "20",
        },
        reportedUser: {
            id: 2,
            status: true,
            image: "./images/male2.jpg",
            gender: "Male",
            name: "Mark Jason",
            username: "mark.jason",
            email: "mark@email.com",
            phone: "+1-321-666-789",
            registered: "02/10/2022",
            age: "24",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing.",
            interest: ["Reading", "Movies", "Painting"],
        },
        reason: "Lorem dummy text of printing & typesetting industry of printing & typesetting industry.",
        date: "16/12/2022",
    },
    {
        id: 2,
        user: {
            id: 4,
            status: true,
            image: "./images/female4.jpg",
            gender: "Female",
            name: " Marco Alves",
            username: "marco.alves",
            email: "marco.alves@email.com",
            phone: "+1-985-999-625",
            registered: "22/09/2022",
            age: "19",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Painting", "Writing", "Gaming"],
            price: "15",
            commission: "10",
        },
        reportedUser: {
            id: 5,
            status: false,
            image: "./images/male2.jpg",
            gender: "Male",
            name: "Isidro Haris",
            username: "isidro",
            email: "isidro@email.com",
            phone: "+1-206-396-1973",
            registered: "22/09/2022",
            age: "31",
            location: "Abc address",
            about:
                "Lorem Ipsum is text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Shooting", "Baseball", "Boxing"],
        },
        reason: "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        date: "15/12/2022",
    },
    {
        id: 3,
        user: {
            id: 1,
            image: "./images/female1.jpg",
            name: "Ogasawara Katsumi",
            username: "ogasawara.katsumi",
            email: "ogasawara@email.com",
            phone: "+1-123-456-789",
            age: "25",
            location: "Abc address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Swimming", "Movies", "Nightout"],
            price: "20",
        },
        reportedUser: {
            id: 2,
            status: true,
            image: "./images/male2.jpg",
            gender: "Male",
            name: "Mark Jason",
            username: "mark.jason",
            email: "mark@email.com",
            phone: "+1-321-666-789",
            registered: "02/10/2022",
            age: "24",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing.",
            interest: ["Reading", "Movies", "Painting"],
        },
        reason: "Text of printing & typesetting industry of printing & typesetting industry.",
        date: "02/12/2022",
    },
    {
        id: 4,
        user: {
            id: 6,
            status: true,
            image: "./images/female3.jpg",
            gender: "Female",
            name: "Okasawara Karsumi",
            username: "okasawara.karsumi",
            email: "okasawara@email.com",
            phone: "+1-984-456-987",
            registered: "18/09/2022",
            age: "20",
            location: "Abc address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Swimming", "Gaming", "Movies", "Surfing"],
            price: "25",
            commission: "13",
        },
        reportedUser: {
            id: 2,
            status: true,
            image: "./images/male2.jpg",
            gender: "Male",
            name: "Mark Jason",
            username: "mark.jason",
            email: "mark@email.com",
            phone: "+1-321-666-789",
            registered: "02/10/2022",
            age: "24",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing.",
            interest: ["Reading", "Movies", "Painting"],
        },
        reason: "Lorem Ipsum is simply dummy text of printing industry.",
        date: "22/11/2022",
    },
    {
        id: 5,
        user: {
            id: 1,
            status: true,
            image: "./images/female1.jpg",
            gender: "Female",
            name: "Ogasawara Katsumi",
            username: "ogasawara.katsumi",
            email: "ogasawara@email.com",
            phone: "+1-123-456-789",
            registered: "08/10/2022",
            age: "25",
            location: "Abc address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Swimming", "Movies", "Nightout"],
            price: "20",
            commission: "10",
        },
        reportedUser: {
            id: 5,
            status: false,
            image: "./images/male2.jpg",
            gender: "Male",
            name: "Isidro Haris",
            username: "isidro",
            email: "isidro@email.com",
            phone: "+1-206-396-1973",
            registered: "22/09/2022",
            age: "31",
            location: "Abc address",
            about:
                "Lorem Ipsum is text of printing & typesetting industry of printing & typesetting industry.",
            interest: ["Shooting", "Baseball", "Boxing"],
        },
        reason: "Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        date: "13/11/2022",
    },
    {
        id: 6,
        user: {
            id: 2,
            status: true,
            image: "./images/female2.jpg",
            gender: "Female",
            name: "Stepan Assonov",
            username: "stepan.assonov",
            email: "stepan@email.com",
            phone: "+1-321-666-789",
            registered: "02/10/2022",
            age: "24",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing.",
            interest: ["Reading", "Movies", "Painting"],
            price: "30",
            commission: "20",
        },
        reportedUser: {
            id: 2,
            status: true,
            image: "./images/male2.jpg",
            gender: "Male",
            name: "Mark Jason",
            username: "mark.jason",
            email: "mark@email.com",
            phone: "+1-321-666-789",
            registered: "02/10/2022",
            age: "24",
            location: "Xyz address",
            about:
                "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing.",
            interest: ["Reading", "Movies", "Painting"],
        },
        reason: "Lorem Ipsum is simply dummy text of printing & typesetting industry of printing & typesetting industry.",
        date: "06/11/2022",
    },
];

export const notifications = [
    {
        id: 1,
        text:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        date: "Dec 19, 2022",
        time: "02:00 PM",
        unread: true,
    },
    {
        id: 2,
        text:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry and typesetting industry.",
        date: "Dec 19, 2022",
        time: "01:40 PM",
        unread: true,
    },
    {
        id: 3,
        text:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        date: "Dec 18, 2022",
        time: "09:13 PM",
        unread: false,
    },
    {
        id: 4,
        text:
            "Lorem Ipsum is text of the printing and typesetting industry.",
        date: "Dec 18, 2022",
        time: "06:38 PM",
        unread: false,
    },
    {
        id: 5,
        text:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        date: "Dec 18, 2022",
        time: "01:49 AM",
        unread: false,
    },
    {
        id: 6,
        text:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        date: "Dec 18, 2022",
        time: "01:05 AM",
        unread: false,
    },
    {
        id: 7,
        text:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        date: "Dec 17, 2022",
        time: "10:52 PM",
        unread: false,
    },
];
